### ISSUE TITLE
How to Timeout on c.Expect()? 

### ISSUE THREAD

**Issue by rfay** [Netflix/go-expect#5]
This is really useful, but debugging an expect scenario is pretty harsh right now, you just end up with a hang in the middle of a test, which is not good.

1. Is there a way to provide a timeout to c.Expect()? Is that easy to implement? It wasn't obvious to me with a casual review. I'm quite surprised it doesn't have that by default.
2. It's super important to be able to see what's going on in the whole expect scenario, and it seems completely obscured at this point. Suggestions about how to debug c.Expect()?

Thanks for doing this and maintaining it!

**Comment by hinshun** [comment]
Hi @rfay, I usually make sure I follow up all my github notifications but somehow this one was missed, sorry!

> Is there a way to provide a timeout to c.Expect()? Is that easy to implement? It wasn't obvious to me with a casual review. I'm quite surprised it doesn't have that by default.

I understand that `tcl-expect` have timeouts, and at one point `go-expect` had something like `c.Expect(expect.String("Something"), expect.WithTimeout(time.Second)` available but I feel they are inherently racy and there usually is a non-racy way of writing the same thing. Do you have an example where you will find this useful?

> It's super important to be able to see what's going on in the whole expect scenario, and it seems completely obscured at this point. Suggestions about how to debug c.Expect()?

Yes you can use the options `expect.WithExpectObserver` and `expect.WithSendObserver` to understand what's causing your tests to fail. I haven't had the time to introduce default options for those to `go-expect` but you would write something like this:

```
func expectNoError(t *testing.T) expect.ConsoleOpt {
	return expect.WithExpectObserver(
		func(matcher expect.Matcher, buf string, err error) {
			if matcher == nil && err != nil {
				t.Errorf("Error occured while matching %q: %s\n%s", buf, err, string(debug.Stack()))
			} else if err != nil {
				t.Errorf("Failed to find %v in %q: %s\n%s", matcher.Criteria(), buf, err, string(debug.Stack()))
			}
		},
	)
}

func sendNoError(t *testing.T) expect.ConsoleOpt {
	return expect.WithSendObserver(
		func(msg string, n int, err error) {
			if err != nil {
				t.Errorf("Failed to send %q: %s\n%s", msg, err, string(debug.Stack()))
			}
			if len(msg) != n {
				t.Errorf("Only sent %d of %d bytes for %q\n%s", n, len(msg), msg, string(debug.Stack()))
			}
		},
	)
}

func TestSomething(t *testing.T) {
    c, err := expect.NewConsole(expect.WithStdin(ptm), expect.WithStdout(term, f, tf), expect.WithCloser(pts, ptm, tf), expectNoError(t), sendNoError(t))

}
```

**Comment by rfay** [comment]
Thanks so much for these suggestions. The basic problem is that nearly any test you can imagine can result in un-debuggable results, which can (and very often do) include hangs, meaning you don't even find out until go test kills it, and then you have no information. And... as you mention it's difficult to debug interactively.  At this point, we don't envision being able to use go-expect at all just because it appears to be a maintenance nightmare. It works for the most trivial of situations, where the thing you're testing is completely predictable, but when anything goes wrong, there's no way out.

It looks like the Observer is a good way to gather some info. But in the situation here, it doesn't do any good because you don't get it until something lets the process go.

In our case, over in survey, we tried to test our binary, but something completely caused the stdio to fail, and nothing about the survey.Input functionality worked in a test environment. I was able to experiment successfully with altering/extending survey's tests (using go-expect) (https://github.com/rfay/survey/blob/8673f66923e6f3de1c2468a3158f84184b2423df/select_examples_test.go#L144) but completely failed with trying the same thing running our binary (ddev) https://github.com/rfay/survey/blob/8673f66923e6f3de1c2468a3158f84184b2423df/select_examples_test.go#L249 - Survey's terminal interaction seemed not to work at all with it and I couldn't figure out any path forward.

**Comment by hinshun** [comment]
You can follow the output without waiting for the go test timeout. For example, you can multiplex the stdout to a file on disk which you can tail to follow along.

```go
func TestSomething(t *testing.T) {
	logFileName := fmt.Sprintf("%s.log", t.Name())
	logFile, err := os.OpenFile(logFileName, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
	require.NoError(t, err)
	defer logFile.Close()

	c, state, err := vt10x.NewVT10XConsole(expect.WithStdout(logFile))
	// In a separate terminal you can `tail -f <test-name>.log`.
}
```
A test suite we wrote for an internal product at Netflix executes all these tests in parallel `t.Parallel()`, with each `go test` go-routine spawning its own virtual terminal to test the interactive application. Perhaps we can write some utility in `go-expect` that creates a temporary serial console so you can do something like `screen <test-name>tty`? I'm open to ideas.

I wrote a simple example for `ddev` that works on OSX / Linux. Unfortunately I don't have a Windows machine to test this: https://github.com/hinshun/ddevexpect

**Comment by rfay** [comment]
Wow, thanks so much for that. Now that I've got the PR that adds survey wrapped (except for testing) I'm going to circle back around and take a look at your example and pursue this a bit farther. Thanks so much!

**Comment by rfay** [comment]
Oh, and to react to the rest, yes, ddev runs and is tested on Windows and Linux and macOS.
winpty works great (as a helper binary, and it's bundled with git-bash) but I'm not sure how or whether it would help go-expect, but it's the standard way to run a `winpty docker run -it <something> bash` for example. 

But yeah, any testing technique we use has to work with macOS, Windows, and Linux.

**Comment by rfay** [comment]
@hinshun Does that mean that https://github.com/hinshun/vt10x is also incompatible with Windows, so couldn't be used for testing there either?

**Comment by hinshun** [comment]
No, `vt10x` is decoupled from ptys so it should work on Windows. That said, I don't own a Windows machine so I haven't tested it.

**Comment by rfay** [comment]
Excellent, thanks!
